replicaCount: 2

image:
  repository: "<aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/django-app-ecr"
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

config:
  DJANGO_DEBUG: "False"
  DJANGO_SECRET_KEY: "change-me"

autoscaling:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
