apiVersion: v1
kind: ConfigMap
metadata:
  name: django-app-config
  labels:
    app: django-app
data:
  DJANGO_DEBUG: {{ .Values.config.DJANGO_DEBUG | quote }}
  DJANGO_SECRET_KEY: {{ .Values.config.DJANGO_SECRET_KEY | quote }}
