apiVersion: v1
kind: ConfigMap
metadata:
  name: django-app-config
data:
  DJANGO_DEBUG: {{ .Values.config.DJANGO_DEBUG | quote }}
  DJANGO_SECRET_KEY: {{ .Values.config.DJANGO_SECRET_KEY | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.config.DJANGO_ALLOWED_HOSTS | quote }}
  DB_HOST: {{ .Values.config.DB_HOST | quote }}
  DB_PORT: {{ .Values.config.DB_PORT | quote }}
  DB_NAME: {{ .Values.config.DB_NAME | quote }}
  DB_USER: {{ .Values.config.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.config.DB_PASSWORD | quote }}
